### ISSUE TITLE
Not connecting on 3.0.0

### ISSUE THREAD

**Issue by Kvalnar** [bitfocus/companion-module-birddog-central#12]
Connected to Central on 2.4.2 but no longer connecting. 

LOG:
system: ** Starting Connection from "C:\Program Files\Companion\resources\module-legacy\manifests\companion-module-birddog-central\index.js" **
system: ** Connection started **
Starting up module class: k
Sentry disabled
Module-host accepted registration
error: Error initializing module: s is not a function

**Comment by bryce-seifert** [comment]
The module has been updated to v3, and should be in the Companion beta builds tomorrow. Let me know if you run into any issues.
