### ISSUE TITLE
Control router source selection

### ISSUE THREAD

**Issue by jibberjabberish** [bitfocus/companion-module-birddog-central#13]
Probably the most important/Useful feature to me is ability to "switch scenes" on a router (Pro version), similar to Blackmagic ATEM or OBS. And feedback on which source is active.

**Comment by bryce-seifert** [comment]
This is currently possible with the 'Connect Source to Router' action and the 'Source Connected to Router' feedback.

If there is something not working, feel free to open up the issues again.
