### ISSUE TITLE
Failure to connect to Central

### ISSUE THREAD

**Issue by atsnelson** [bitfocus/companion-module-birddog-central#15]
I've been trying to connect the module to my BD Central service on two different PC's. Both PC's have been running both BD Central and Companion and both machines have no issues connecting the vMix module to vMix. I get connection failure using the Central web UI address (same as PC's) in this case 192.168.1.200 and 192.168.1.136. Companion version 3.2 Beta.

**Comment by bryce-seifert** [comment]
@atsnelson What does the error say in the Companion log?

**Comment by atsnelson** [comment]
Hi Bryce. Thanks for reaching out. This could totally be a fault at my end. I'm just not sure what else to try. I've attached a screen shot of the companion UI. Error is under status "connection failure". Keep in mind I'm using the 3.2 Beta version of Companion because I didn't think your version 2.0.0.0 was in the current stable version? Cheers Jason
![Companion Screen Shot2](https://github.com/bitfocus/companion-module-birddog-central/assets/121831150/b508dbf8-3e2e-4109-8243-49eada98b06a)
![Companion Screen Shot2](https://github.com/bitfocus/companion-module-birddog-central/assets/121831150/48390c97-4c5f-4206-a729-8723448ec83b)

**Comment by bryce-seifert** [comment]
@atsnelson Thanks for clarifying. If you click on the tab that says “log” in the upper right, are there any additional error messages?

**Comment by atsnelson** [comment]
Nothing shows in the log unfortunately. I have noticed something though. If  I set the device IP to 192.168.1.200 it just set there saying connecting but doesn't and if I add the port 192.168.1.200:3020 it says connection failure straight away. 
![Companion I P without port set](https://github.com/bitfocus/companion-module-birddog-central/assets/121831150/31154d7e-4389-486b-b0c9-06c8e2da6288)
![Companion I P with port set](https://github.com/bitfocus/companion-module-birddog-central/assets/121831150/c7e6a5d5-7dc1-40d7-863b-7f323ffec640)

**Comment by atsnelson** [comment]
I tried turning off Windows10 firewall to see if that allowed the BD Central module to connect, unfortunately not.,

**Comment by bryce-seifert** [comment]
@atsnelson You should not enter the port, only the IP address. The module/API use a different port for communication.

What happens if you open the module log (the `>_` icon next to trash can icon on the module) and then restart the module? Are there any errors in that log?

**Comment by atsnelson** [comment]
Okay so the first time Companion is started. the BD Central status says connecting (but doesn't) If I click on the label to check the device IP and then click save, the status after 2 seconds changes to connection failure. It does this until companion is shut down and restarted. Here's a screen shot of the module log. I stopped it and restarted. Cheers Jason 
![debug](https://github.com/bitfocus/companion-module-birddog-central/assets/121831150/6056f7f5-5041-4b46-b142-de5bbb93fb55)

**Comment by bryce-seifert** [comment]
Alright thank you. And just to be clear: this works when Central and Companion are on different computers, right? The only issue is when they're on the same machine?

**Comment by atsnelson** [comment]
No. I haven’t tried it like that. I’ve tried two computers both with Companion and BD Central. Not across a network. Cheers

**Comment by pricard32** [comment]
![image](https://github.com/bitfocus/companion-module-birddog-central/assets/29844015/e9c38860-2ee1-4c4d-8875-a95dad935c0c)

I'm also not able to connect

**Comment by fishbrainsD** [comment]
I am also unable to connect. Same error as @pricard32. Using companion ver 3.1.2 (stable)

**Comment by bryce-seifert** [comment]
@pricard32 @fishbrainsD For your specific errors, please try the 3.2 beta. The version shipped with 3.1.2 isn't updated for v3. Let me know if you still get the error on 3.2

**Comment by pricard32** [comment]
Still not working for me, but different errors.
Same as : @atsnelson 

Tested Central + Companion on the same computer
I've tried with loopback IP and actual IP.

**Comment by fishbrainsD** [comment]
Thank you @bryce-seifert I have tried it with 3.2 beta and it now says it is connected. All my sources and destinations etc are listed when I create a button. However, the buttons I have created to connect sources and destinations do not seem to so anything. I am using the web buttons and I have tried this with individual destinations and groups.  There is nothing in the module log after pressing a button.  Should there be?

**Comment by bryce-seifert** [comment]
@pricard32 @fishbrainsD @atsnelson 
I found/fixed some bugs that I hope address the issues. There are in the very latest 3.2 beta.
Please give this a try, and let me know how it goes.

**Comment by bryce-seifert** [comment]
I got confirmation that the latest beta solved this issue for some on the Facebook group, so I'm going to close. Let me know if there are still issues.

**Comment by fishbrainsD** [comment]
Yes this latest beta is working for me. Thanks @bryce-seifert
